name: Build and Deploy to EdgeOne

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0' # 选择适合的 Node.js 版本
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npx quartz build -d docs
      
      - name: Deploy to EdgeOne Pages
        run: npx edgeone pages deploy ./public -n some-notes -t ${{ secrets.EDGEONE_API_TOKEN }}
        env:
          EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}